platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: e34a96a0963fee6d6bf50f6fc184797014464719

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: 065639a0a76c5f7c564509b8fd8b64f7949da4f5

- name: LINUX
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 6efc4f3044eab8d6131fe2155b95e6344adfa29e

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: 0353cd0a2eeda903738f5daa74384affaeb9da65

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: dev-esp32
  commit: 3062b35895f35ff8b87b5ed9189c72922795b75b

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 3132855d1873ce065059e3647be58f6b608c3a1f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 53b61a46c27406623cdf7e727a2958aca98a1cda
