platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: e34a96a0963fee6d6bf50f6fc184797014464719

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: 065639a0a76c5f7c564509b8fd8b64f7949da4f5

- name: LINUX
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 3857d8a677d0ac837766a55cf011124500a4cc1b

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: 4624775565923d41390c7cc809e6d578568d320d

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: dev-esp32
  commit: b1ba7e457f801f69975429dcd9cd4dafcd1e9232

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 3132855d1873ce065059e3647be58f6b608c3a1f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 53b61a46c27406623cdf7e727a2958aca98a1cda
